# Generated by Django 5.1.6 on 2025-03-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dept',
            name='loc',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='emp',
            name='ename',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='emp',
            name='job',
            field=models.CharField(max_length=250),
        ),
    ]
