# Generated by Django 5.1.6 on 2025-03-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dept_dname_alter_dept_loc_alter_emp_ename_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dept',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emp',
            table=None,
        ),
    ]
