# Generated by Django 5.1.6 on 2025-03-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dept_table_alter_emp_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dept',
            table='dept',
        ),
        migrations.AlterModelTable(
            name='emp',
            table='emp',
        ),
    ]
